import { Link } from 'react-router-dom'
import { ContentPage, Note, Section, type TocEntry } from './ContentPage.tsx'

/**
 * Privacy policy.
 *
 * Written from the data flows in the code, not from a template. The parts a
 * template omits are the parts that matter here: the user's goal text goes to
 * Anthropic, the values it needs go to whichever seller was paid, and payments
 * are written to a public ledger that no one can erase. Section 5 exists as its
 * own clause because the right to deletion genuinely stops at the chain.
 *
 * A published privacy policy is also a condition of the Google OAuth client, so
 * this page is load-bearing rather than decorative.
 */

const TOC: TocEntry[] = [
  { id: 'who', label: 'Who we are' },
  { id: 'collect', label: 'What we hold' },
  { id: 'why', label: 'Why we hold it' },
  { id: 'sharing', label: 'Where it goes' },
  { id: 'chain', label: 'The permanent part' },
  { id: 'storage', label: 'Cookies and storage' },
  { id: 'keeping', label: 'How long' },
  { id: 'rights', label: 'Your rights' },
  { id: 'security', label: 'Security' },
  { id: 'transfers', label: 'Transfers' },
  { id: 'children', label: 'Age' },
  { id: 'changes', label: 'Changes' },
  { id: 'contact', label: 'Contact' },
]

export function PrivacyPage() {
  return (
    <ContentPage
      eyebrow="Privacy"
      title={
        <>
          What we hold,
          <br />
          and where it goes.
        </>
      }
      lede={
        <>
          Trident runs an agent that pays for things on your behalf, so it handles a sign-in,
          a wallet key, and everything you ask the agent to do. This page says what each of
          those means in practice, including the parts that are less comfortable than a
          template would make them sound.
        </>
      }
      updated="12 August 2026"
      toc={TOC}
      numbered
    >
      <Section id="who" heading="Who we are" numbered>
        <p className="doc-p">
          Trident is an independent project, not a company. It is built and run by one
          person, and the source is public at{' '}
          <a
            className="doc-a"
            href="https://github.com/Anazodo-C/trident-agent"
            target="_blank"
            rel="noreferrer noopener"
          >
            github.com/Anazodo-C/trident-agent
          </a>
          , so anything described on this page can be checked against the code that does it.
        </p>
        <p className="doc-p">
          We decide what happens to the information described here, which makes us
          responsible for it. Everything on this page, including any request about your own
          data, reaches us at{' '}
          <a
            className="doc-a"
            href="https://x.com/tridentagent"
            target="_blank"
            rel="noreferrer noopener"
          >
            x.com/tridentagent
          </a>
          .
        </p>
      </Section>

      <Section id="collect" heading="What we hold" numbered>
        <p className="doc-p">
          Everything below is either something you gave us or something the agent produced
          while working for you.
        </p>
        <div className="doc-scroll">
          <table className="doc-table">
            <thead>
              <tr>
                <th>Data</th>
                <th>Where it comes from</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td className="k">
                  Email address
                  <br />
                  and Google account id
                </td>
                <td>Google, if you sign in with Google</td>
              </tr>
              <tr>
                <td className="k">Wallet address</td>
                <td>Your wallet, if you sign in by signing a message</td>
              </tr>
              <tr>
                <td className="k">Agent wallet address</td>
                <td>Generated by us when you set a passphrase</td>
              </tr>
              <tr>
                <td className="k">Encrypted wallet key</td>
                <td>Generated by us, encrypted with your passphrase</td>
              </tr>
              <tr>
                <td className="k">
                  Spending cap and
                  <br />
                  network preferences
                </td>
                <td>Your settings</td>
              </tr>
              <tr>
                <td className="k">The goals you type</td>
                <td>You, every time you ask the agent for something</td>
              </tr>
              <tr>
                <td className="k">Run history</td>
                <td>
                  Each step: the service called, the values sent, the cost, the transaction
                  reference, and a summary of what came back
                </td>
              </tr>
              <tr>
                <td className="k">Conversations</td>
                <td>Follow-up questions you ask about a run</td>
              </tr>
              <tr>
                <td className="k">Server logs</td>
                <td>
                  Standard request records from our hosting providers, including IP address
                </td>
              </tr>
            </tbody>
          </table>
        </div>
        <Note tag="Not held">
          <p>
            We never store your passphrase, and we never store your wallet key in a form we
            can read. We do not use analytics or advertising trackers, and we do not sell or
            rent anything on this page to anyone.
          </p>
        </Note>
      </Section>

      <Section id="why" heading="Why we hold it" numbered>
        <ol className="doc-sub">
          <li>
            <strong>To sign you in and keep you signed in.</strong> Your email or wallet
            address identifies your account.
          </li>
          <li>
            <strong>To give your agent a wallet.</strong> The encrypted key is what lets the
            agent pay for the calls you approve.
          </li>
          <li>
            <strong>To do what you asked.</strong> Your goal has to be read, planned against
            the catalog, and turned into calls.
          </li>
          <li>
            <strong>To show you what happened and what it cost,</strong> and to let a failed
            run resume without paying twice.
          </li>
          <li>
            <strong>To keep the service working and secure:</strong> diagnosing faults,
            enforcing spending limits, preventing abuse.
          </li>
        </ol>
        <p className="doc-p">
          Where the law requires a basis for processing, ours is the performance of our
          agreement with you for everything except security and abuse prevention, which rests
          on our legitimate interest in keeping the service running.
        </p>
      </Section>

      <Section id="sharing" heading="Where it goes" numbered>
        <p className="doc-p">
          Using Trident necessarily sends some of your information to other companies. This is
          the complete list.
        </p>
        <div className="doc-scroll">
          <table className="doc-table">
            <thead>
              <tr>
                <th>Recipient</th>
                <th>What they receive</th>
                <th>Why</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td className="k">Anthropic</td>
                <td>
                  <strong>The text of your goal</strong>, the shortlist of candidate services,
                  and the results returned, so a plain-language answer can be written
                </td>
                <td>Planning and summarising</td>
              </tr>
              <tr>
                <td className="k">
                  The service
                  <br />
                  you are paying
                </td>
                <td>
                  <strong>The values that call needs:</strong> a city, a wallet address, a
                  search term, whatever your goal required
                </td>
                <td>It is the call you paid for</td>
              </tr>
              <tr>
                <td className="k">Public blockchains</td>
                <td>
                  Your agent&apos;s wallet address, the amount, the recipient and the time.{' '}
                  <strong>Permanent and public.</strong>
                </td>
                <td>Settling payment</td>
              </tr>
              <tr>
                <td className="k">Google</td>
                <td>Sign-in details, if you use Google</td>
                <td>Sign-in</td>
              </tr>
              <tr>
                <td className="k">WalletConnect</td>
                <td>
                  Basic app-usage telemetry, sent by the wallet-connection library when the app
                  loads, before any wallet is connected
                </td>
                <td>Wallet connection support</td>
              </tr>
              <tr>
                <td className="k">Circle</td>
                <td>
                  Requests for the service catalog and for cross-chain transfer attestations
                </td>
                <td>Catalog and settlement</td>
              </tr>
              <tr>
                <td className="k">Hosting providers</td>
                <td>Standard server and delivery logs, including IP address</td>
                <td>Running the site and the API</td>
              </tr>
            </tbody>
          </table>
        </div>
        <Note tag="The one to be aware of" tone="money">
          <p>
            <strong>What you type goes to a third party.</strong> Your goal is read by
            Anthropic&apos;s model in order to plan the work, and the values it needs go to
            whichever service performs it. Do not put anything in a goal that you would not
            want handled by those companies: passwords, private keys, or personal details
            about other people.
          </p>
        </Note>
        <p className="doc-p">
          Our fonts are served from this site rather than from a font CDN, so loading a page
          does not tell anyone else that you visited.
        </p>
        <p className="doc-p">
          We will also disclose information where the law genuinely requires it, and if
          Trident is ever transferred to another operator, in which case this page will say so
          before it takes effect.
        </p>
      </Section>

      <Section id="chain" heading="The permanent part" numbered>
        <p className="doc-p">
          Payments settle on public blockchains. That has a consequence worth stating on its
          own rather than burying in a list.
        </p>
        <p className="doc-p">
          Every payment your agent makes is written to a public ledger that anyone can read
          and <strong>nobody can edit or erase</strong>, not you, not us, not the companies
          who operate those networks. The record shows your agent&apos;s wallet address, what
          it paid, to whom, and when. It is pseudonymous rather than anonymous: the address is
          not your name, but anything that ever links the two links them for good.
        </p>
        <p className="doc-plainly">
          <strong>Plainly:</strong> we can delete your account and everything in our database.
          We cannot delete a transaction, and no one can.
        </p>
      </Section>

      <Section id="storage" heading="Cookies and storage" numbered>
        <p className="doc-p">
          <strong>Trident sets no cookies.</strong> There is no advertising, no analytics, no
          tracking pixel, and nothing to consent to, which is why you have not been shown a
          cookie banner.
        </p>
        <p className="doc-p">
          We store exactly two things in your browser, and only while you are using the app:
        </p>
        <ul className="doc-ul">
          <li className="doc-li">
            <strong>A sign-in token,</strong> kept so you are not asked to sign in again on
            every page. Signing out or clearing site data removes it.
          </li>
          <li className="doc-li">
            <strong>Your unlocked wallet key,</strong> held in memory only for as long as the
            tab is open. It is never written to disk, and closing or refreshing the tab
            discards it.
          </li>
        </ul>
        <p className="doc-p">
          Both are necessary to provide the service you asked for. Neither is used to profile
          you or to follow you anywhere else.
        </p>
      </Section>

      <Section id="keeping" heading="How long we keep it" numbered>
        <ol className="doc-sub">
          <li>
            <strong>Account details and your encrypted key</strong> are kept until you delete
            your account.
          </li>
          <li>
            <strong>Run history and conversations</strong> are kept until you delete them or
            your account, because they are the record of what you spent and what you got.
          </li>
          <li>
            <strong>Server logs</strong> are kept for the retention period of our hosting
            providers, which is short and measured in days.
          </li>
        </ol>
        <p className="doc-p">Deleting your account removes all of the above from our database.</p>
      </Section>

      <Section id="rights" heading="Your rights" numbered>
        <p className="doc-p">
          Depending on where you live you may have some or all of the following rights. We
          honour them regardless of whether your jurisdiction grants them.
        </p>
        <ol className="doc-sub">
          <li>
            <strong>See what we hold.</strong> Ask, and we will send you your data.
          </li>
          <li>
            <strong>Correct it</strong> if it is wrong.
          </li>
          <li>
            <strong>Delete it.</strong> We will remove your account and everything associated
            with it.
          </li>
          <li>
            <strong>Take it with you,</strong> in a machine-readable form.
          </li>
          <li>
            <strong>Object to processing</strong> that rests on our legitimate interest.
          </li>
          <li>
            <strong>Complain</strong> to your data-protection authority if you think we have
            handled this badly.
          </li>
        </ol>
        <Note tag="Two limits, stated honestly" tone="stop">
          <p>
            <strong>Deletion does not reach the blockchain.</strong> We will erase our records.
            Transactions already settled remain public forever, and that is outside
            anyone&apos;s control.
          </p>
          <p className="mt-2">
            <strong>Deleting your account deletes your encrypted key.</strong> If the wallet
            still holds funds, withdraw them first. Once the record is gone we cannot help you
            reach them, because we could never read the key in the first place.
          </p>
        </Note>
        <p className="doc-p">
          Message us at <a
            className="doc-a"
            href="https://x.com/tridentagent"
            target="_blank"
            rel="noreferrer noopener"
          >
            x.com/tridentagent
          </a> and we will respond within 30 days.
        </p>
      </Section>

      <Section id="security" heading="Security" numbered>
        <ol className="doc-sub">
          <li>The database is encrypted at rest.</li>
          <li>
            Your wallet key is encrypted with a key derived from your passphrase, which we
            never store, so we cannot read it.
          </li>
          <li>Secrets are filtered out of our logs.</li>
          <li>Traffic between you and us is encrypted in transit.</li>
        </ol>
        <p className="doc-p">
          There is one part of this you should understand rather than take on trust: to make a
          payment, your key is decrypted in your browser and then sent to our server to sign
          the transaction. It is used in memory and never written down, but it does leave your
          device in use. The{' '}
          <Link className="doc-a" to="/docs#security">
            documentation
          </Link>{' '}
          explains exactly how, and no security measure protects you if your passphrase is weak
          or reused.
        </p>
      </Section>

      <Section id="transfers" heading="International transfers" numbered>
        <p className="doc-p">
          Trident&apos;s servers, and the companies listed in section 4, are located in various
          countries including the United States and the European Union. Using the service
          transfers your information to those countries. Where required, we rely on the
          transfer mechanisms those providers make available, such as standard contractual
          clauses.
        </p>
      </Section>

      <Section id="children" heading="Age" numbered>
        <p className="doc-p">
          Trident is for people aged 18 and over. We do not knowingly collect anything from a
          child. If you believe a child has created an account, write to us and we will remove
          it.
        </p>
      </Section>

      <Section id="changes" heading="Changes" numbered>
        <p className="doc-p">
          When this page changes materially we will update the date at the top and, for
          anything significant, tell you in the app before it takes effect. Previous versions
          are in the{' '}
          <a
            className="doc-a"
            href="https://github.com/Anazodo-C/trident-agent"
            target="_blank"
            rel="noreferrer noopener"
          >
            public repository&apos;s history
          </a>
          , so you can see exactly what changed and when.
        </p>
      </Section>

      <Section id="contact" heading="Contact" numbered>
        <p className="doc-p">
          Questions, requests, or complaints about anything on this page go to <a
            className="doc-a"
            href="https://x.com/tridentagent"
            target="_blank"
            rel="noreferrer noopener"
          >
            x.com/tridentagent
          </a>.
        </p>
      </Section>
    </ContentPage>
  )
}
